apiVersion: v1
kind: Service
metadata:
  name: careercoach-service
spec:
  selector:
    app: careercoach-app
  ports:
    - port: 80
      targetPort: 8501  # default port for Streamlit
  type: NodePort